In [ ]:
import pandas as pd

In [ ]:
emp_rate=pd.read_csv('/content/졸업생의 취업 현황 (대학) 2024(원본).csv', header = 3) #csv파일 4번째 행을 컬럼으로 읽어오기
pd.set_option('display.max_columns', None) #head로 불러올 때 ...으로 생략되지 않게 하는 코드
emp_rate.head(10)

,기준연도,학교종류,설립구분,지역,상태,학교명,단과대학,학과(전공),구분,학과특성,졸업자(A),Unnamed: 11,취업자(B),Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,진학자(C),Unnamed: 25,입대자(D),취업불가능자(E),Unnamed: 28,외국인유학생(F),Unnamed: 30,제외인정자(G),Unnamed: 32,기타,Unnamed: 34,미상,Unnamed: 36,취업률(%)\n[B/{A-(C+D+E+F+G)x100,입학\n당시\n기취업자,Unnamed: 39,교내취업자,Unnamed: 41,유지\n취업률,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,건강보험\n직장가입자,NaN,해외\n취업자,NaN,농림어업\n종사자,NaN,개인창작\n활동\n종사자,NaN,1인\n창(사)업자,NaN,프리랜서,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1차,NaN,NaN,2차,NaN,NaN,3차,NaN,NaN,4차,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,남,여,남,여,남,여,남,여,남,여,남,여,남,여,남,여,NaN,남,여,남,여,남,여,남,여,남,여,NaN,남,여,남,여,계,남,여,계,남,여,계,남,여,계,남,여
4,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,간호학과,주간,일반과정,35,142,28,123,0,0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0,0,0,0,7,18,0,0,85.9,2,21,0,2,94.7,89.3,95.9,90.1,82.1,91.9,87.4,71.4,91.1,84.1,71.4,87
5,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,경영물류학과,주간,일반과정,28,2,18,1,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,3,0,0,0,7,1,0,0,70.4,0,0,0,0,89.5,94.4,0,89.5,94.4,0,78.9,83.3,0,78.9,83.3,0
6,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,경찰소방학과,주간,일반과정,10,7,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,1,6,5,0,0,31.3,0,0,1,1,80,75,100,80,75,100,80,75,100,60,75,0
7,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,귀금속주얼리학과,주간,일반과정,7,14,6,4,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,0,0,2,1,7,0,0,57.9,0,0,0,1,100,100,100,100,100,100,90,83.3,100,70,66.7,75
8,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,물리치료학과,주간,일반과정,28,25,24,22,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,0,0,0,4,2,0,0,88.7,4,0,0,0,89.1,95.8,81.8,84.8,95.8,72.7,84.8,95.8,72.7,84.8,95.8,72.7
9,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,방사선학과,주간,일반과정,20,24,16,19,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,1,4,4,0,0,81.4,1,0,0,0,94.3,100,89.5,88.6,87.5,89.5,82.9,81.3,84.2,77.1,75,78.9

In [ ]:
emp_rate.drop(index=[0, 1, 2, 3], inplace=True) #0부터 3까지의 행 삭제
emp_rate = emp_rate.reset_index(drop=True) #인덱스를 다시 1부터 재정리

#남 여 구별되어 있는 컬럼 공통되는 컬럼으로 병합 & 컬럼 명 변경
emp_rate['1'] = pd.to_numeric(emp_rate['졸업자(A)'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 11'], errors='coerce') #컬럼 1과 2의 값을 더하기 위해 명시적으로 데이터를 숫자형으로 변환
emp_rate.drop(['졸업자(A)', 'Unnamed: 11'], axis=1, inplace=True)

emp_rate['2'] = pd.to_numeric(emp_rate['취업자(B)'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 13'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 14'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 15'], errors='coerce') +pd.to_numeric(emp_rate['Unnamed: 16'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 17'], errors='coerce') +pd.to_numeric(emp_rate['Unnamed: 18'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 19'], errors='coerce') +pd.to_numeric(emp_rate['Unnamed: 20'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 21'], errors='coerce') +pd.to_numeric(emp_rate['Unnamed: 22'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 23'], errors='coerce')
emp_rate.drop(['취업자(B)', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
               'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23'], axis=1, inplace=True)

emp_rate['3'] = pd.to_numeric(emp_rate['진학자(C)'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 25'], errors='coerce')
emp_rate.drop(['진학자(C)', 'Unnamed: 25'], axis=1, inplace=True)

emp_rate['4'] = pd.to_numeric(emp_rate['입대자(D)'])
emp_rate.drop(['입대자(D)'], axis=1, inplace=True)

emp_rate['5'] = pd.to_numeric(emp_rate['취업불가능자(E)'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 28'], errors='coerce')
emp_rate.drop(['취업불가능자(E)', 'Unnamed: 28'], axis=1, inplace=True)

emp_rate['6'] = pd.to_numeric(emp_rate['외국인유학생(F)'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 30'], errors='coerce')
emp_rate.drop(['외국인유학생(F)', 'Unnamed: 30'], axis=1, inplace=True)

emp_rate['7'] = pd.to_numeric(emp_rate['제외인정자(G)'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 32'], errors='coerce')
emp_rate.drop(['제외인정자(G)', 'Unnamed: 32'], axis=1, inplace=True)

emp_rate['8'] = pd.to_numeric(emp_rate['기타'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 34'], errors='coerce')
emp_rate.drop(['기타', 'Unnamed: 34'], axis=1, inplace=True)

emp_rate['9'] = pd.to_numeric(emp_rate['미상'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 36'], errors='coerce')
emp_rate.drop(['미상', 'Unnamed: 36'], axis=1, inplace=True)

emp_rate['10'] = pd.to_numeric(emp_rate['입학\n당시\n기취업자'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 39'], errors='coerce')
emp_rate.drop(['입학\n당시\n기취업자', 'Unnamed: 39'], axis=1, inplace=True)

emp_rate['11'] = pd.to_numeric(emp_rate['교내취업자'], errors='coerce') + pd.to_numeric(emp_rate['Unnamed: 41'], errors='coerce')
emp_rate.drop(['교내취업자', 'Unnamed: 41'], axis=1, inplace=True)

emp_rate.drop(['유지\n취업률', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
               'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53'], axis=1, inplace=True) #유지\n취업률\n(수시)는 2024년도부터 유지\n취업률 로 명칭이 바뀜

emp_rate.rename(columns={'취업률(%)\n[B/{A-(C+D+E+F+G)x100':'0'}, inplace=True)

new_order = ['기준연도', '학교종류', '설립구분', '지역', '상태', '학교명', '단과대학', '학과(전공)', '구분', '학과특성', '1','2','3','4','5','6','7','8','9','0','10','11']
emp_rate = emp_rate[new_order]

emp_rate.rename(columns={'0':'취업률(%)[B/{A-(C+D+E+F+G)x100', '1':'졸업자(A)', '2':'취업자(B)', '3':'진학자(C)', '4':'입대자(D)', '5':'취업불가능자(E)',
                         '6':'외국인유학생(F)', '7':'제외인정자(G)', '8':'기타', '9':'미상', '10':'입학 당시 기취업자','11':'교내취업자'}, inplace=True)

emp_rate.head()

,기준연도,학교종류,설립구분,지역,상태,학교명,단과대학,학과(전공),구분,학과특성,졸업자(A),취업자(B),진학자(C),입대자(D),취업불가능자(E),외국인유학생(F),제외인정자(G),기타,미상,취업률(%)[B/{A-(C+D+E+F+G)x100,입학 당시 기취업자,교내취업자
0,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,간호학과,주간,일반과정,177.0,152.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,85.9,23.0,2.0
1,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,경영물류학과,주간,일반과정,30.0,19.0,0.0,0.0,0.0,3.0,0.0,8.0,0.0,70.4,0.0,0.0
2,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,경찰소방학과,주간,일반과정,17.0,5.0,0.0,0.0,0.0,0.0,1.0,11.0,0.0,31.3,0.0,2.0
3,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,귀금속주얼리학과,주간,일반과정,21.0,11.0,0.0,0.0,0.0,0.0,2.0,8.0,0.0,57.9,0.0,1.0
4,2023.0,대학교,사립,경남,기존,가야대학교(김해),단과대구분없음,물리치료학과,주간,일반과정,53.0,47.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,88.7,4.0,0.0

In [ ]:
emp_rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9916 entries, 0 to 9915
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   기준연도                         9915 non-null   float64
 1   학교종류                         9915 non-null   object
 2   설립구분                         9915 non-null   object
 3   지역                           9915 non-null   object
 4   상태                           9915 non-null   object
 5   학교명                          9915 non-null   object
 6   단과대학                         9915 non-null   object
 7   학과(전공)                       9915 non-null   object
 8   구분                           9915 non-null   object
 9   학과특성                         9915 non-null   object
 10  졸업자(A)                       9907 non-null   float64
 11  취업자(B)                       9912 non-null   float64
 12  진학자(C)                       9915 non-null   float64
 13  입대자(D)                       9915 non-null   float64
 14  취업불가능자(E)                    9915 non-null   float64
 15  외국인유학생(F)                    9915 non-null   float64
 16  제외인정자(G)                     9915 non-null   float64
 17  기타                           9915 non-null   float64
 18  미상                           9915 non-null   float64
 19  취업률(%)[B/{A-(C+D+E+F+G)x100  9915 non-null   float64
 20  입학 당시 기취업자                   9913 non-null   float64
 21  교내취업자                        9915 non-null   float64
dtypes: float64(13), object(9)
memory usage: 1.7+ MB

In [ ]:
emp_rate.to_csv("employment_rate_2024.csv", index=False)